/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT INTO Country VALUES ('CS','Serbia ja Montenegro')
	   INSERT INTO Country VALUES ('LV','Läti')
	   INSERT INTO Country VALUES ('LY','Liibüa')
	   INSERT INTO Country VALUES ('MA','Maroko')
	   INSERT INTO Country VALUES ('MD','Moldova')
	   INSERT INTO Country VALUES ('MG','Madagaskar')
	   INSERT INTO Country VALUES ('MH','Marshalli saared')
	   INSERT INTO Country VALUES ('MK','Makedoonia')
	   INSERT INTO Country VALUES ('ML','Mali')
	   INSERT INTO Country VALUES ('MN','Mongoolia')
	   INSERT INTO Country VALUES ('MO','Macau')
	   INSERT INTO Country VALUES ('MP','Põhja-Mariaanid')
	   INSERT INTO Country VALUES ('MQ','Martinique')
	   INSERT INTO Country VALUES ('MS','Montserrat')
	   INSERT INTO Country VALUES ('MT','Malta')
	   INSERT INTO Country VALUES ('MU','Mauritius')
	   INSERT INTO Country VALUES ('MV','Maldiivid')
	   INSERT INTO Country VALUES ('MW','Malawi')
	   INSERT INTO Country VALUES ('MX','Mehhiko')
	   INSERT INTO Country VALUES ('MY','Malaisia')
	   INSERT INTO Country VALUES ('MZ','Mosambiik')
	   INSERT INTO Country VALUES ('NA','Namiibia')
	   INSERT INTO Country VALUES ('NC','Uus-Kaledoonia')
	   INSERT INTO Country VALUES ('NF','Norfolki saared')
	   INSERT INTO Country VALUES ('NG','Nigeeria')
	   INSERT INTO Country VALUES ('NI','Nikaraagua')
	   INSERT INTO Country VALUES ('NL','Holland')
	   INSERT INTO Country VALUES ('NO','Norra')
	   INSERT INTO Country VALUES ('NP','Nepaal')
	   INSERT INTO Country VALUES ('NR','Nauru')
	   INSERT INTO Country VALUES ('NZ','Uus-Meremaa')
	   INSERT INTO Country VALUES ('OM','Omaan')
	   INSERT INTO Country VALUES ('PA','Panama')
	   INSERT INTO Country VALUES ('PE','Peruu')
	   INSERT INTO Country VALUES ('PF','Prantsuse Polüneesia')
	   INSERT INTO Country VALUES ('PG','Paapua Uus-Guinea')
	   INSERT INTO Country VALUES ('PH','Filipiinid')
	   INSERT INTO Country VALUES ('PL','Poola')
	   INSERT INTO Country VALUES ('PM','St. Pierre ja Miquelon')
	   INSERT INTO Country VALUES ('PN','Pitcairni saar')
	   INSERT INTO Country VALUES ('PR','Puerto Rico')
	   INSERT INTO Country VALUES ('PT','Portugal')
	   INSERT INTO Country VALUES ('PW','Palau')
	   INSERT INTO Country VALUES ('PY','Paraguay')
	   INSERT INTO Country VALUES ('QA','Qatar')
	   INSERT INTO Country VALUES ('RE','Reunion')
	   INSERT INTO Country VALUES ('LU','Luksemburg')
	   INSERT INTO Country VALUES ('RO','Rumeenia')
	   INSERT INTO Country VALUES ('RW','Rwanda')
	   INSERT INTO Country VALUES ('SA','Saudi Araabia')
	   INSERT INTO Country VALUES ('SB','Saalomoni saared')
	   INSERT INTO Country VALUES ('SC','Seišellid')
	   INSERT INTO Country VALUES ('SD','Sudaan')
	   INSERT INTO Country VALUES ('SE','Rootsi')
	   INSERT INTO Country VALUES ('SG','Singapur')
	   INSERT INTO Country VALUES ('SH','St. Helena')
	   INSERT INTO Country VALUES ('SI','Sloveenia')
	   INSERT INTO Country VALUES ('AD','Andorra')
	   INSERT INTO Country VALUES ('AE','Araabia Ühendemiraadid')
	   INSERT INTO Country VALUES ('AF','Afganistaan')
	   INSERT INTO Country VALUES ('AG','Antigua ja Barbuda')
	   INSERT INTO Country VALUES ('AI','Anguilla')
	   INSERT INTO Country VALUES ('AL','Albaania')
	   INSERT INTO Country VALUES ('AN','Hollandi Antillid')
	   INSERT INTO Country VALUES ('AO','Angoola')
	   INSERT INTO Country VALUES ('AR','Argentiina')
	   INSERT INTO Country VALUES ('AS','Ameerika Samoa')
	   INSERT INTO Country VALUES ('AT','Austria')
	   INSERT INTO Country VALUES ('AU','Austraalia')
	   INSERT INTO Country VALUES ('AW','Aruuba')
	   INSERT INTO Country VALUES ('AZ','Aserbaidžaan')
	   INSERT INTO Country VALUES ('BA','Bosnia Hertsegoviina')
	   INSERT INTO Country VALUES ('BB','Barbados')
	   INSERT INTO Country VALUES ('BE','Belgia')
	   INSERT INTO Country VALUES ('BG','Bulgaaria')
	   INSERT INTO Country VALUES ('BH','Bahrain')
	   INSERT INTO Country VALUES ('BI','Burundi')
	   INSERT INTO Country VALUES ('BJ','Benin')
	   INSERT INTO Country VALUES ('BN','Brunei Darussalam')
	   INSERT INTO Country VALUES ('BR','Brasiilia')
	   INSERT INTO Country VALUES ('BS','Bahama')
	   INSERT INTO Country VALUES ('BT','Bhutan')
	   INSERT INTO Country VALUES ('BW','Botswaana')
	   INSERT INTO Country VALUES ('BZ','Belize')
	   INSERT INTO Country VALUES ('CA','Kanada')
	   INSERT INTO Country VALUES ('CC','Kookossaared')
	   INSERT INTO Country VALUES ('CH','Šveits')
	   INSERT INTO Country VALUES ('CI','Elevandiluurannik')
	   INSERT INTO Country VALUES ('CK','Cooki saared')
	   INSERT INTO Country VALUES ('CL','Tšiili')
	   INSERT INTO Country VALUES ('CM','Kamerun')
	   INSERT INTO Country VALUES ('CN','Hiina')
	   INSERT INTO Country VALUES ('CR','Costa Rica')
	   INSERT INTO Country VALUES ('CU','Kuuba')
	   INSERT INTO Country VALUES ('CX','Jõulusaar')
	   INSERT INTO Country VALUES ('CZ','Tšehhi Vabariik')
	   INSERT INTO Country VALUES ('DJ','Djibouti')
	   INSERT INTO Country VALUES ('DK','Taani')
	   INSERT INTO Country VALUES ('DM','Dominica')
	   INSERT INTO Country VALUES ('DO','Dominica Vabariik')
	   INSERT INTO Country VALUES ('DZ','Alžeeria')
	   INSERT INTO Country VALUES ('EC','Ecuador')
	   INSERT INTO Country VALUES ('EE','Eesti')
	   INSERT INTO Country VALUES ('EG','Egiptus')
	   INSERT INTO Country VALUES ('LC','Saint Lucia')
	   INSERT INTO Country VALUES ('LR','Libeeria')
	   INSERT INTO Country VALUES ('LS','Lesotho')
	   INSERT INTO Country VALUES ('LT','Leedu')
	   INSERT INTO Country VALUES ('BF','Burkina Faso')
	   INSERT INTO Country VALUES ('BM','Bermuuda')
	   INSERT INTO Country VALUES ('BO','Boliivia')
	   INSERT INTO Country VALUES ('ZZ','Merel')
	   INSERT INTO Country VALUES ('BY','Valgevene')
	   INSERT INTO Country VALUES ('CF','Kesk-Aafrika Vabariik')
	   INSERT INTO Country VALUES ('CO','Kolumbia')
	   INSERT INTO Country VALUES ('CV','Roheneemesaared')
	   INSERT INTO Country VALUES ('DE','Saksamaa')
	   INSERT INTO Country VALUES ('SK','Slovakkia')
	   INSERT INTO Country VALUES ('SN','Senegal')
	   INSERT INTO Country VALUES ('GU','Guam')
	   INSERT INTO Country VALUES ('GZ','Gaza sektor')
	   INSERT INTO Country VALUES ('HR','Horvaatia')
	   INSERT INTO Country VALUES ('IL','Iisrael')
	   INSERT INTO Country VALUES ('IR','Iraan')
	   INSERT INTO Country VALUES ('KH','Kambodža')
	   INSERT INTO Country VALUES ('KN','Saint Kitts - Nevis')
	   INSERT INTO Country VALUES ('KZ','Kasahstan')
	   INSERT INTO Country VALUES ('YT','Mayotte')
	   INSERT INTO Country VALUES ('LI','Liechtenstein')
	   INSERT INTO Country VALUES ('MC','Monaco')
	   INSERT INTO Country VALUES ('MR','Mauritaania')
	   INSERT INTO Country VALUES ('NE','Niger')
	   INSERT INTO Country VALUES ('NU','Niue')
	   INSERT INTO Country VALUES ('PK','Pakistan')
	   INSERT INTO Country VALUES ('RU','Vene Föderatsioon')
	   INSERT INTO Country VALUES ('AM','Armeenia')
	   INSERT INTO Country VALUES ('BD','Bangladesh')
	   INSERT INTO Country VALUES ('CG','Kongo')
	   INSERT INTO Country VALUES ('CY','Küpros')
	   INSERT INTO Country VALUES ('SJ','Svalbard ja Jan Mayen')
	   INSERT INTO Country VALUES ('SY','Süüria Araabia Vabariik')
	   INSERT INTO Country VALUES ('TZ','Tansaania Ühendatud Vabariik')
	   INSERT INTO Country VALUES ('ZM','Sambia')
	   INSERT INTO Country VALUES ('ER','Eritrea')
	   INSERT INTO Country VALUES ('GB','Suurbrittannia')
	   INSERT INTO Country VALUES ('IN','India')
	   INSERT INTO Country VALUES ('KG','Kõrgõzstan')
	   INSERT INTO Country VALUES ('LK','Sri Lanka')
	   INSERT INTO Country VALUES ('US','Ameerika Ühendriigid')
	   INSERT INTO Country VALUES ('XZ','Rahvusvaheline tsoon')
	   INSERT INTO Country VALUES ('SL','Sierra Leone')
	   INSERT INTO Country VALUES ('SM','San Marino')
	   INSERT INTO Country VALUES ('SO','Somaalia')
	   INSERT INTO Country VALUES ('SR','Suriname')
	   INSERT INTO Country VALUES ('ST','Sao Tome ja Principe')
	   INSERT INTO Country VALUES ('SV','El Salvador')
	   INSERT INTO Country VALUES ('SZ','Svaasimaa')
	   INSERT INTO Country VALUES ('TC','Turks ja Caicos')
	   INSERT INTO Country VALUES ('TD','Tšaad')
	   INSERT INTO Country VALUES ('TF','Prantsuse alad lõunas ja Antarktikas')
	   INSERT INTO Country VALUES ('TG','Togo')
	   INSERT INTO Country VALUES ('TH','Tai')
	   INSERT INTO Country VALUES ('TJ','Tadžikistan')
	   INSERT INTO Country VALUES ('TK','Tokelau')
	   INSERT INTO Country VALUES ('TM','Türkmenistan')
	   INSERT INTO Country VALUES ('TN','Tuneesia')
	   INSERT INTO Country VALUES ('TO','Tonga')
	   INSERT INTO Country VALUES ('TR','Türgi')
	   INSERT INTO Country VALUES ('TT','Trinidad ja Tobago')
	   INSERT INTO Country VALUES ('TV','Tuvalu')
	   INSERT INTO Country VALUES ('TW','Taiwan')
	   INSERT INTO Country VALUES ('UA','Ukraina')
	   INSERT INTO Country VALUES ('UG','Uganda')
	   INSERT INTO Country VALUES ('UM','Ameerika Ühendriikide hajasaared')
	   INSERT INTO Country VALUES ('UY','Uruguay')
	   INSERT INTO Country VALUES ('UZ','Usbekistan')
	   INSERT INTO Country VALUES ('VA','Vatikani Linnriik')
	   INSERT INTO Country VALUES ('VC','Saint Vincent ja Grenadiinid')
	   INSERT INTO Country VALUES ('VE','Venetsueela')
	   INSERT INTO Country VALUES ('VG','Briti Neitsisaared')
	   INSERT INTO Country VALUES ('VI','Ühendriikide Neitsisaared')
	   INSERT INTO Country VALUES ('VN','Vietnam')
	   INSERT INTO Country VALUES ('VU','Vanuatu')
	   INSERT INTO Country VALUES ('WE','Jordani Läänekallas')
	   INSERT INTO Country VALUES ('WF','Wallise ja Futuna saared')
	   INSERT INTO Country VALUES ('WS','Samoa')
	   INSERT INTO Country VALUES ('YE','Jeemen')
	   INSERT INTO Country VALUES ('ZA','Lõuna-Aafrika')
	   INSERT INTO Country VALUES ('ZR','Sair')
	   INSERT INTO Country VALUES ('ZW','Zimbabwe')
	   INSERT INTO Country VALUES ('GS','Lõuna-Gruusia ja Lõuna Võileiva saared')
	   INSERT INTO Country VALUES ('CD','Kongo Demokraatlik Vabariik')
	   INSERT INTO Country VALUES ('AQ','Antarktika')
	   INSERT INTO Country VALUES ('OT','Muu')
	   INSERT INTO Country VALUES ('TA','Tahiiti')
	   INSERT INTO Country VALUES ('MM','Myanmar (Former Burma)')
	   INSERT INTO Country VALUES ('TL','Ida-Timor')
	   INSERT INTO Country VALUES ('ES','Hispaania')
	   INSERT INTO Country VALUES ('ET','Etioopia')
	   INSERT INTO Country VALUES ('FI','Soome')
	   INSERT INTO Country VALUES ('FJ','Fidži')
	   INSERT INTO Country VALUES ('FK','Falklandi saared')
	   INSERT INTO Country VALUES ('FM','Mikroneesia')
	   INSERT INTO Country VALUES ('FO','Fääri saared')
	   INSERT INTO Country VALUES ('FR','Prantsusmaa')
	   INSERT INTO Country VALUES ('GA','Gabon')
	   INSERT INTO Country VALUES ('GD','Grenada')
	   INSERT INTO Country VALUES ('GE','Gruusia')
	   INSERT INTO Country VALUES ('GF','Prantsuse Guajaana')
	   INSERT INTO Country VALUES ('GH','Ghana')
	   INSERT INTO Country VALUES ('GI','Gibraltar')
	   INSERT INTO Country VALUES ('GL','Gröönimaa')
	   INSERT INTO Country VALUES ('GM','Gambia')
	   INSERT INTO Country VALUES ('GN','Guinea')
	   INSERT INTO Country VALUES ('GP','Guadeloupe')
	   INSERT INTO Country VALUES ('GQ','Ekvatoriaalne Guinea')
	   INSERT INTO Country VALUES ('GR','Kreeka')
	   INSERT INTO Country VALUES ('GT','Guatemala')
	   INSERT INTO Country VALUES ('GW','Guinea-Bissau')
	   INSERT INTO Country VALUES ('GY','Guyana')
	   INSERT INTO Country VALUES ('HK','Hong Kong')
	   INSERT INTO Country VALUES ('HM','Heardi ja Mcdonaldi saared')
	   INSERT INTO Country VALUES ('HN','Honduras')
	   INSERT INTO Country VALUES ('HT','Haiti')
	   INSERT INTO Country VALUES ('HU','Ungari')
	   INSERT INTO Country VALUES ('ID','Indoneesia')
	   INSERT INTO Country VALUES ('IE','Iirimaa')
	   INSERT INTO Country VALUES ('IO','India ookeani territoorium')
	   INSERT INTO Country VALUES ('IQ','Iraak')
	   INSERT INTO Country VALUES ('IS','Island')
	   INSERT INTO Country VALUES ('IT','Itaalia')
	   INSERT INTO Country VALUES ('JM','Jamaika')
	   INSERT INTO Country VALUES ('JO','Jordaania')
	   INSERT INTO Country VALUES ('JP','Jaapan')
	   INSERT INTO Country VALUES ('KE','Keenia')
	   INSERT INTO Country VALUES ('KI','Kiribati')
	   INSERT INTO Country VALUES ('KM','Comoros')
	   INSERT INTO Country VALUES ('KP','Korea Demokraatlik Rahvavabariik (Põhja-)')
	   INSERT INTO Country VALUES ('KR','Korea Vabariik (Lõuna-)')
	   INSERT INTO Country VALUES ('KW','Kuveit')
	   INSERT INTO Country VALUES ('KY','Caymani saared')
	   INSERT INTO Country VALUES ('LA','Lao Demokraatlik Rahvavabariik')
	   INSERT INTO Country VALUES ('LB','Liibanon')
	   INSERT INTO Country VALUES ('EH','Lääne-Sahaara')
	   INSERT INTO Country VALUES ('ME','Montenegro')
	   INSERT INTO Country VALUES ('','')