CREATE TABLE [dbo].[CMR]
(
	ID int IDENTITY(1000000,1) NOT NULL PRIMARY KEY UNIQUE,
	SenderID int NULL,
	ConsigneeID int NULL,
	DeliveryPlace varchar(100) NOT NULL,
	DeliveryCountry varchar(100) NOT NULL,
	TakingPlace varchar(100) NOT NULL,
	TakingCountry varchar(100) NOT NULL,
	AttachedDocuments varchar(500) NOT NULL,
	CarrierID int NULL,
	NextCarrierID int NULL,
	ClassValue varchar(10) NOT NULL,
	Num int NOT NULL,
	Letter varchar(2) DEFAULT ('') NOT NULL,
	ADR varchar(100) DEFAULT ('') NOT NULL,
	SendInstruction varchar(500) NOT NULL,
	SenderPaymentID int NOT NULL,
	ConsigneePaymentID int NOT NULL,
	SpecialAgreements varchar(500) NOT NULL,
	PaymentInstruction varchar(30) NOT NULL,
	CMRValid bit NOT NULL,
	EstablieshedIn varchar(50) NOT NULL,
	EstablieshedDate datetime NOT NULL,
	TimeOfDep datetime NOT NULL,
	TransportID int NOT NULL,
	TransportID2 int NULL,
	UserCreated varchar(50) NULL,
 	ManifestId int NULL
)
