#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class BeLogDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertCountry(Country instance);
    partial void UpdateCountry(Country instance);
    partial void DeleteCountry(Country instance);
    partial void InsertOrderItem(OrderItem instance);
    partial void UpdateOrderItem(OrderItem instance);
    partial void DeleteOrderItem(OrderItem instance);
    partial void InsertPaymentInfo(PaymentInfo instance);
    partial void UpdatePaymentInfo(PaymentInfo instance);
    partial void DeletePaymentInfo(PaymentInfo instance);
    partial void InsertTransport(Transport instance);
    partial void UpdateTransport(Transport instance);
    partial void DeleteTransport(Transport instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertManifest(Manifest instance);
    partial void UpdateManifest(Manifest instance);
    partial void DeleteManifest(Manifest instance);
    partial void InsertCMR(CMR instance);
    partial void UpdateCMR(CMR instance);
    partial void DeleteCMR(CMR instance);
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    partial void InsertOrderDispatch(OrderDispatch instance);
    partial void UpdateOrderDispatch(OrderDispatch instance);
    partial void DeleteOrderDispatch(OrderDispatch instance);
    #endregion
		
		public BeLogDB() : 
				base(global::DataAccessLayer.Properties.Settings.Default.BeLogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BeLogDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeLogDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeLogDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BeLogDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<Country> Countries
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		public System.Data.Linq.Table<OrderItem> OrderItems
		{
			get
			{
				return this.GetTable<OrderItem>();
			}
		}
		
		public System.Data.Linq.Table<PaymentInfo> PaymentInfos
		{
			get
			{
				return this.GetTable<PaymentInfo>();
			}
		}
		
		public System.Data.Linq.Table<Transport> Transports
		{
			get
			{
				return this.GetTable<Transport>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Manifest> Manifests
		{
			get
			{
				return this.GetTable<Manifest>();
			}
		}
		
		public System.Data.Linq.Table<CMR> CMRs
		{
			get
			{
				return this.GetTable<CMR>();
			}
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		public System.Data.Linq.Table<OrderDispatch> OrderDispatches
		{
			get
			{
				return this.GetTable<OrderDispatch>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Address;
		
		private string _Country;
		
		private int _CompanyType;
		
		private string _ContactPerson;
		
		private string _Fax;
		
		private string _Phone;
		
		private EntitySet<Invoice> _Invoices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnCompanyTypeChanging(int value);
    partial void OnCompanyTypeChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public Company()
		{
			this._Invoices = new EntitySet<Invoice>(new Action<Invoice>(this.attach_Invoices), new Action<Invoice>(this.detach_Invoices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyType", DbType="Int NOT NULL")]
		public int CompanyType
		{
			get
			{
				return this._CompanyType;
			}
			set
			{
				if ((this._CompanyType != value))
				{
					this.OnCompanyTypeChanging(value);
					this.SendPropertyChanging();
					this._CompanyType = value;
					this.SendPropertyChanged("CompanyType");
					this.OnCompanyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="VarChar(50)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Invoice", Storage="_Invoices", ThisKey="ID", OtherKey="CompanyToID")]
		public EntitySet<Invoice> Invoices
		{
			get
			{
				return this._Invoices;
			}
			set
			{
				this._Invoices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.CompanyTo = this;
		}
		
		private void detach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.CompanyTo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Country")]
	public partial class Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CountryCode;
		
		private string _CountryName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnCountryNameChanging(string value);
    partial void OnCountryNameChanged();
    #endregion
		
		public Country()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="VarChar(50)")]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this.OnCountryNameChanging(value);
					this.SendPropertyChanging();
					this._CountryName = value;
					this.SendPropertyChanged("CountryName");
					this.OnCountryNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderItem")]
	public partial class OrderItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CMRID;
		
		private string _MarkAndNum;
		
		private int _NumOfPackages;
		
		private string _PackagingMethod;
		
		private string _GoodsNature;
		
		private string _StartNumber;
		
		private decimal _Weight;
		
		private decimal _Volume;
		
		private EntityRef<CMR> _CMR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCMRIDChanging(System.Nullable<int> value);
    partial void OnCMRIDChanged();
    partial void OnMarkAndNumChanging(string value);
    partial void OnMarkAndNumChanged();
    partial void OnNumOfPackagesChanging(int value);
    partial void OnNumOfPackagesChanged();
    partial void OnPackagingMethodChanging(string value);
    partial void OnPackagingMethodChanged();
    partial void OnGoodsNatureChanging(string value);
    partial void OnGoodsNatureChanged();
    partial void OnStartNumberChanging(string value);
    partial void OnStartNumberChanged();
    partial void OnWeightChanging(decimal value);
    partial void OnWeightChanged();
    partial void OnVolumeChanging(decimal value);
    partial void OnVolumeChanged();
    #endregion
		
		public OrderItem()
		{
			this._CMR = default(EntityRef<CMR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMRID", DbType="Int")]
		public System.Nullable<int> CMRID
		{
			get
			{
				return this._CMRID;
			}
			set
			{
				if ((this._CMRID != value))
				{
					if (this._CMR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCMRIDChanging(value);
					this.SendPropertyChanging();
					this._CMRID = value;
					this.SendPropertyChanged("CMRID");
					this.OnCMRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkAndNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MarkAndNum
		{
			get
			{
				return this._MarkAndNum;
			}
			set
			{
				if ((this._MarkAndNum != value))
				{
					this.OnMarkAndNumChanging(value);
					this.SendPropertyChanging();
					this._MarkAndNum = value;
					this.SendPropertyChanged("MarkAndNum");
					this.OnMarkAndNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfPackages", DbType="Int NOT NULL")]
		public int NumOfPackages
		{
			get
			{
				return this._NumOfPackages;
			}
			set
			{
				if ((this._NumOfPackages != value))
				{
					this.OnNumOfPackagesChanging(value);
					this.SendPropertyChanging();
					this._NumOfPackages = value;
					this.SendPropertyChanged("NumOfPackages");
					this.OnNumOfPackagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackagingMethod", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PackagingMethod
		{
			get
			{
				return this._PackagingMethod;
			}
			set
			{
				if ((this._PackagingMethod != value))
				{
					this.OnPackagingMethodChanging(value);
					this.SendPropertyChanging();
					this._PackagingMethod = value;
					this.SendPropertyChanged("PackagingMethod");
					this.OnPackagingMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodsNature", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GoodsNature
		{
			get
			{
				return this._GoodsNature;
			}
			set
			{
				if ((this._GoodsNature != value))
				{
					this.OnGoodsNatureChanging(value);
					this.SendPropertyChanging();
					this._GoodsNature = value;
					this.SendPropertyChanged("GoodsNature");
					this.OnGoodsNatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string StartNumber
		{
			get
			{
				return this._StartNumber;
			}
			set
			{
				if ((this._StartNumber != value))
				{
					this.OnStartNumberChanging(value);
					this.SendPropertyChanging();
					this._StartNumber = value;
					this.SendPropertyChanged("StartNumber");
					this.OnStartNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(12,2) NOT NULL")]
		public decimal Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(12,2) NOT NULL")]
		public decimal Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CMR_OrderItem", Storage="_CMR", ThisKey="CMRID", OtherKey="ID", IsForeignKey=true)]
		public CMR CMR
		{
			get
			{
				return this._CMR.Entity;
			}
			set
			{
				CMR previousValue = this._CMR.Entity;
				if (((previousValue != value) 
							|| (this._CMR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CMR.Entity = null;
						previousValue.OrderItems.Remove(this);
					}
					this._CMR.Entity = value;
					if ((value != null))
					{
						value.OrderItems.Add(this);
						this._CMRID = value.ID;
					}
					else
					{
						this._CMRID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CMR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentInfo")]
	public partial class PaymentInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CompanyID;
		
		private decimal _CarriageCharges;
		
		private decimal _Deductions;
		
		private decimal _Saldo;
		
		private decimal _Supplements;
		
		private decimal _OtherCharges;
		
		private string _Currency;
		
		private EntitySet<CMR> _CMRs;
		
		private EntitySet<CMR> _CMRs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCompanyIDChanging(System.Nullable<int> value);
    partial void OnCompanyIDChanged();
    partial void OnCarriageChargesChanging(decimal value);
    partial void OnCarriageChargesChanged();
    partial void OnDeductionsChanging(decimal value);
    partial void OnDeductionsChanged();
    partial void OnSaldoChanging(decimal value);
    partial void OnSaldoChanged();
    partial void OnSupplementsChanging(decimal value);
    partial void OnSupplementsChanged();
    partial void OnOtherChargesChanging(decimal value);
    partial void OnOtherChargesChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    #endregion
		
		public PaymentInfo()
		{
			this._CMRs = new EntitySet<CMR>(new Action<CMR>(this.attach_CMRs), new Action<CMR>(this.detach_CMRs));
			this._CMRs1 = new EntitySet<CMR>(new Action<CMR>(this.attach_CMRs1), new Action<CMR>(this.detach_CMRs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int")]
		public System.Nullable<int> CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarriageCharges", DbType="Decimal(10,2) NOT NULL")]
		public decimal CarriageCharges
		{
			get
			{
				return this._CarriageCharges;
			}
			set
			{
				if ((this._CarriageCharges != value))
				{
					this.OnCarriageChargesChanging(value);
					this.SendPropertyChanging();
					this._CarriageCharges = value;
					this.SendPropertyChanged("CarriageCharges");
					this.OnCarriageChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deductions", DbType="Decimal(10,2) NOT NULL")]
		public decimal Deductions
		{
			get
			{
				return this._Deductions;
			}
			set
			{
				if ((this._Deductions != value))
				{
					this.OnDeductionsChanging(value);
					this.SendPropertyChanging();
					this._Deductions = value;
					this.SendPropertyChanged("Deductions");
					this.OnDeductionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(10,2) NOT NULL")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplements", DbType="Decimal(10,2) NOT NULL")]
		public decimal Supplements
		{
			get
			{
				return this._Supplements;
			}
			set
			{
				if ((this._Supplements != value))
				{
					this.OnSupplementsChanging(value);
					this.SendPropertyChanging();
					this._Supplements = value;
					this.SendPropertyChanged("Supplements");
					this.OnSupplementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherCharges", DbType="Decimal(10,2) NOT NULL")]
		public decimal OtherCharges
		{
			get
			{
				return this._OtherCharges;
			}
			set
			{
				if ((this._OtherCharges != value))
				{
					this.OnOtherChargesChanging(value);
					this.SendPropertyChanging();
					this._OtherCharges = value;
					this.SendPropertyChanged("OtherCharges");
					this.OnOtherChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentInfo_CMR", Storage="_CMRs", ThisKey="ID", OtherKey="ConsigneePaymentID")]
		public EntitySet<CMR> CMRs
		{
			get
			{
				return this._CMRs;
			}
			set
			{
				this._CMRs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentInfo_CMR1", Storage="_CMRs1", ThisKey="ID", OtherKey="SenderPaymentID")]
		public EntitySet<CMR> CMRs1
		{
			get
			{
				return this._CMRs1;
			}
			set
			{
				this._CMRs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.ConsigneePayment = this;
		}
		
		private void detach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.ConsigneePayment = null;
		}
		
		private void attach_CMRs1(CMR entity)
		{
			this.SendPropertyChanging();
			entity.SenderPayment = this;
		}
		
		private void detach_CMRs1(CMR entity)
		{
			this.SendPropertyChanging();
			entity.SenderPayment = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transport")]
	public partial class Transport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RegisterNumber;
		
		private string _Model;
		
		private EntitySet<CMR> _CMRs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRegisterNumberChanging(string value);
    partial void OnRegisterNumberChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    #endregion
		
		public Transport()
		{
			this._CMRs = new EntitySet<CMR>(new Action<CMR>(this.attach_CMRs), new Action<CMR>(this.detach_CMRs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RegisterNumber
		{
			get
			{
				return this._RegisterNumber;
			}
			set
			{
				if ((this._RegisterNumber != value))
				{
					this.OnRegisterNumberChanging(value);
					this.SendPropertyChanging();
					this._RegisterNumber = value;
					this.SendPropertyChanged("RegisterNumber");
					this.OnRegisterNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transport_CMR", Storage="_CMRs", ThisKey="ID", OtherKey="TransportID")]
		public EntitySet<CMR> CMRs
		{
			get
			{
				return this._CMRs;
			}
			set
			{
				this._CMRs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.Transport = this;
		}
		
		private void detach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.Transport = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BFUser")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LoginUserName;
		
		private string _LoginPassword;
		
		private string _ApplicationRights;
		
		private string _Abreviation;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _PhoneNumber;
		
		private EntitySet<Invoice> _Invoices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginUserNameChanging(string value);
    partial void OnLoginUserNameChanged();
    partial void OnLoginPasswordChanging(string value);
    partial void OnLoginPasswordChanged();
    partial void OnApplicationRightsChanging(string value);
    partial void OnApplicationRightsChanged();
    partial void OnAbreviationChanging(string value);
    partial void OnAbreviationChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public User()
		{
			this._Invoices = new EntitySet<Invoice>(new Action<Invoice>(this.attach_Invoices), new Action<Invoice>(this.detach_Invoices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginUserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LoginUserName
		{
			get
			{
				return this._LoginUserName;
			}
			set
			{
				if ((this._LoginUserName != value))
				{
					this.OnLoginUserNameChanging(value);
					this.SendPropertyChanging();
					this._LoginUserName = value;
					this.SendPropertyChanged("LoginUserName");
					this.OnLoginUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LoginPassword
		{
			get
			{
				return this._LoginPassword;
			}
			set
			{
				if ((this._LoginPassword != value))
				{
					this.OnLoginPasswordChanging(value);
					this.SendPropertyChanging();
					this._LoginPassword = value;
					this.SendPropertyChanged("LoginPassword");
					this.OnLoginPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationRights", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ApplicationRights
		{
			get
			{
				return this._ApplicationRights;
			}
			set
			{
				if ((this._ApplicationRights != value))
				{
					this.OnApplicationRightsChanging(value);
					this.SendPropertyChanging();
					this._ApplicationRights = value;
					this.SendPropertyChanged("ApplicationRights");
					this.OnApplicationRightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abreviation", DbType="VarChar(10)")]
		public string Abreviation
		{
			get
			{
				return this._Abreviation;
			}
			set
			{
				if ((this._Abreviation != value))
				{
					this.OnAbreviationChanging(value);
					this.SendPropertyChanging();
					this._Abreviation = value;
					this.SendPropertyChanged("Abreviation");
					this.OnAbreviationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Invoice", Storage="_Invoices", ThisKey="ID", OtherKey="GeneratedByUserID")]
		public EntitySet<Invoice> Invoices
		{
			get
			{
				return this._Invoices;
			}
			set
			{
				this._Invoices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.GeneratedBy = this;
		}
		
		private void detach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.GeneratedBy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manifest")]
	public partial class Manifest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Departure;
		
		private string _Arrival;
		
		private System.Nullable<System.DateTime> _ManifestDate;
		
		private string _ManifesName;
		
		private System.Nullable<int> _CreatedBy;
		
		private EntitySet<CMR> _CMRs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDepartureChanging(string value);
    partial void OnDepartureChanged();
    partial void OnArrivalChanging(string value);
    partial void OnArrivalChanged();
    partial void OnManifestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnManifestDateChanged();
    partial void OnManifesNameChanging(string value);
    partial void OnManifesNameChanged();
    partial void OnCreatedByChanging(System.Nullable<int> value);
    partial void OnCreatedByChanged();
    #endregion
		
		public Manifest()
		{
			this._CMRs = new EntitySet<CMR>(new Action<CMR>(this.attach_CMRs), new Action<CMR>(this.detach_CMRs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure", DbType="VarChar(50)")]
		public string Departure
		{
			get
			{
				return this._Departure;
			}
			set
			{
				if ((this._Departure != value))
				{
					this.OnDepartureChanging(value);
					this.SendPropertyChanging();
					this._Departure = value;
					this.SendPropertyChanged("Departure");
					this.OnDepartureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrival", DbType="VarChar(50)")]
		public string Arrival
		{
			get
			{
				return this._Arrival;
			}
			set
			{
				if ((this._Arrival != value))
				{
					this.OnArrivalChanging(value);
					this.SendPropertyChanging();
					this._Arrival = value;
					this.SendPropertyChanged("Arrival");
					this.OnArrivalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManifestDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ManifestDate
		{
			get
			{
				return this._ManifestDate;
			}
			set
			{
				if ((this._ManifestDate != value))
				{
					this.OnManifestDateChanging(value);
					this.SendPropertyChanging();
					this._ManifestDate = value;
					this.SendPropertyChanged("ManifestDate");
					this.OnManifestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManifesName", DbType="VarChar(100)")]
		public string ManifesName
		{
			get
			{
				return this._ManifesName;
			}
			set
			{
				if ((this._ManifesName != value))
				{
					this.OnManifesNameChanging(value);
					this.SendPropertyChanging();
					this._ManifesName = value;
					this.SendPropertyChanged("ManifesName");
					this.OnManifesNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="int")]
		public System.Nullable<int> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manifest_CMR", Storage="_CMRs", ThisKey="id", OtherKey="ManifestId")]
		public EntitySet<CMR> CMRs
		{
			get
			{
				return this._CMRs;
			}
			set
			{
				this._CMRs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.Manifest = this;
		}
		
		private void detach_CMRs(CMR entity)
		{
			this.SendPropertyChanging();
			entity.Manifest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CMR")]
	public partial class CMR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _SenderID;
		
		private System.Nullable<int> _ConsigneeID;
		
		private string _DeliveryPlace;
		
		private string _DeliveryCountry;
		
		private string _TakingPlace;
		
		private string _TakingCountry;
		
		private string _AttachedDocuments;
		
		private System.Nullable<int> _CarrierID;
		
		private System.Nullable<int> _NextCarrierID;
		
		private string _ClassValue;
		
		private int _Num;
		
		private string _Letter;
		
		private string _ADR;
		
		private string _SendInstruction;
		
		private int _SenderPaymentID;
		
		private int _ConsigneePaymentID;
		
		private string _SpecialAgreements;
		
		private string _PaymentInstruction;
		
		private bool _CMRValid;
		
		private string _EstablieshedIn;
		
		private System.DateTime _EstablieshedDate;
		
		private System.DateTime _TimeOfDep;
		
		private int _TransportID;
		
		private System.Nullable<int> _TransportID2;
		
		private string _UserCreated;
		
		private System.Nullable<int> _ManifestId;
		
		private EntitySet<OrderItem> _OrderItems;
		
		private EntityRef<PaymentInfo> _ConsigneePayment;
		
		private EntityRef<Manifest> _Manifest;
		
		private EntityRef<Transport> _Transport;
		
		private EntityRef<PaymentInfo> _SenderPayment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSenderIDChanging(System.Nullable<int> value);
    partial void OnSenderIDChanged();
    partial void OnConsigneeIDChanging(System.Nullable<int> value);
    partial void OnConsigneeIDChanged();
    partial void OnDeliveryPlaceChanging(string value);
    partial void OnDeliveryPlaceChanged();
    partial void OnDeliveryCountryChanging(string value);
    partial void OnDeliveryCountryChanged();
    partial void OnTakingPlaceChanging(string value);
    partial void OnTakingPlaceChanged();
    partial void OnTakingCountryChanging(string value);
    partial void OnTakingCountryChanged();
    partial void OnAttachedDocumentsChanging(string value);
    partial void OnAttachedDocumentsChanged();
    partial void OnCarrierIDChanging(System.Nullable<int> value);
    partial void OnCarrierIDChanged();
    partial void OnNextCarrierIDChanging(System.Nullable<int> value);
    partial void OnNextCarrierIDChanged();
    partial void OnClassValueChanging(string value);
    partial void OnClassValueChanged();
    partial void OnNumChanging(int value);
    partial void OnNumChanged();
    partial void OnLetterChanging(string value);
    partial void OnLetterChanged();
    partial void OnADRChanging(string value);
    partial void OnADRChanged();
    partial void OnSendInstructionChanging(string value);
    partial void OnSendInstructionChanged();
    partial void OnSenderPaymentIDChanging(int value);
    partial void OnSenderPaymentIDChanged();
    partial void OnConsigneePaymentIDChanging(int value);
    partial void OnConsigneePaymentIDChanged();
    partial void OnSpecialAgreementsChanging(string value);
    partial void OnSpecialAgreementsChanged();
    partial void OnPaymentInstructionChanging(string value);
    partial void OnPaymentInstructionChanged();
    partial void OnCMRValidChanging(bool value);
    partial void OnCMRValidChanged();
    partial void OnEstablieshedInChanging(string value);
    partial void OnEstablieshedInChanged();
    partial void OnEstablieshedDateChanging(System.DateTime value);
    partial void OnEstablieshedDateChanged();
    partial void OnTimeOfDepChanging(System.DateTime value);
    partial void OnTimeOfDepChanged();
    partial void OnTransportIDChanging(int value);
    partial void OnTransportIDChanged();
    partial void OnTransportID2Changing(System.Nullable<int> value);
    partial void OnTransportID2Changed();
    partial void OnUserCreatedChanging(string value);
    partial void OnUserCreatedChanged();
    partial void OnManifestIdChanging(System.Nullable<int> value);
    partial void OnManifestIdChanged();
    #endregion
		
		public CMR()
		{
			this._OrderItems = new EntitySet<OrderItem>(new Action<OrderItem>(this.attach_OrderItems), new Action<OrderItem>(this.detach_OrderItems));
			this._ConsigneePayment = default(EntityRef<PaymentInfo>);
			this._Manifest = default(EntityRef<Manifest>);
			this._Transport = default(EntityRef<Transport>);
			this._SenderPayment = default(EntityRef<PaymentInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderID", DbType="Int")]
		public System.Nullable<int> SenderID
		{
			get
			{
				return this._SenderID;
			}
			set
			{
				if ((this._SenderID != value))
				{
					this.OnSenderIDChanging(value);
					this.SendPropertyChanging();
					this._SenderID = value;
					this.SendPropertyChanged("SenderID");
					this.OnSenderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsigneeID", DbType="Int")]
		public System.Nullable<int> ConsigneeID
		{
			get
			{
				return this._ConsigneeID;
			}
			set
			{
				if ((this._ConsigneeID != value))
				{
					this.OnConsigneeIDChanging(value);
					this.SendPropertyChanging();
					this._ConsigneeID = value;
					this.SendPropertyChanged("ConsigneeID");
					this.OnConsigneeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryPlace", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DeliveryPlace
		{
			get
			{
				return this._DeliveryPlace;
			}
			set
			{
				if ((this._DeliveryPlace != value))
				{
					this.OnDeliveryPlaceChanging(value);
					this.SendPropertyChanging();
					this._DeliveryPlace = value;
					this.SendPropertyChanged("DeliveryPlace");
					this.OnDeliveryPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryCountry", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DeliveryCountry
		{
			get
			{
				return this._DeliveryCountry;
			}
			set
			{
				if ((this._DeliveryCountry != value))
				{
					this.OnDeliveryCountryChanging(value);
					this.SendPropertyChanging();
					this._DeliveryCountry = value;
					this.SendPropertyChanged("DeliveryCountry");
					this.OnDeliveryCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakingPlace", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TakingPlace
		{
			get
			{
				return this._TakingPlace;
			}
			set
			{
				if ((this._TakingPlace != value))
				{
					this.OnTakingPlaceChanging(value);
					this.SendPropertyChanging();
					this._TakingPlace = value;
					this.SendPropertyChanged("TakingPlace");
					this.OnTakingPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakingCountry", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TakingCountry
		{
			get
			{
				return this._TakingCountry;
			}
			set
			{
				if ((this._TakingCountry != value))
				{
					this.OnTakingCountryChanging(value);
					this.SendPropertyChanging();
					this._TakingCountry = value;
					this.SendPropertyChanged("TakingCountry");
					this.OnTakingCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachedDocuments", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string AttachedDocuments
		{
			get
			{
				return this._AttachedDocuments;
			}
			set
			{
				if ((this._AttachedDocuments != value))
				{
					this.OnAttachedDocumentsChanging(value);
					this.SendPropertyChanging();
					this._AttachedDocuments = value;
					this.SendPropertyChanged("AttachedDocuments");
					this.OnAttachedDocumentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierID", DbType="Int")]
		public System.Nullable<int> CarrierID
		{
			get
			{
				return this._CarrierID;
			}
			set
			{
				if ((this._CarrierID != value))
				{
					this.OnCarrierIDChanging(value);
					this.SendPropertyChanging();
					this._CarrierID = value;
					this.SendPropertyChanged("CarrierID");
					this.OnCarrierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextCarrierID", DbType="Int")]
		public System.Nullable<int> NextCarrierID
		{
			get
			{
				return this._NextCarrierID;
			}
			set
			{
				if ((this._NextCarrierID != value))
				{
					this.OnNextCarrierIDChanging(value);
					this.SendPropertyChanging();
					this._NextCarrierID = value;
					this.SendPropertyChanged("NextCarrierID");
					this.OnNextCarrierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassValue", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ClassValue
		{
			get
			{
				return this._ClassValue;
			}
			set
			{
				if ((this._ClassValue != value))
				{
					this.OnClassValueChanging(value);
					this.SendPropertyChanging();
					this._ClassValue = value;
					this.SendPropertyChanged("ClassValue");
					this.OnClassValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="Int NOT NULL")]
		public int Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Letter", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Letter
		{
			get
			{
				return this._Letter;
			}
			set
			{
				if ((this._Letter != value))
				{
					this.OnLetterChanging(value);
					this.SendPropertyChanging();
					this._Letter = value;
					this.SendPropertyChanged("Letter");
					this.OnLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ADR
		{
			get
			{
				return this._ADR;
			}
			set
			{
				if ((this._ADR != value))
				{
					this.OnADRChanging(value);
					this.SendPropertyChanging();
					this._ADR = value;
					this.SendPropertyChanged("ADR");
					this.OnADRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendInstruction", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string SendInstruction
		{
			get
			{
				return this._SendInstruction;
			}
			set
			{
				if ((this._SendInstruction != value))
				{
					this.OnSendInstructionChanging(value);
					this.SendPropertyChanging();
					this._SendInstruction = value;
					this.SendPropertyChanged("SendInstruction");
					this.OnSendInstructionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderPaymentID", DbType="Int NOT NULL")]
		public int SenderPaymentID
		{
			get
			{
				return this._SenderPaymentID;
			}
			set
			{
				if ((this._SenderPaymentID != value))
				{
					if (this._SenderPayment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSenderPaymentIDChanging(value);
					this.SendPropertyChanging();
					this._SenderPaymentID = value;
					this.SendPropertyChanged("SenderPaymentID");
					this.OnSenderPaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsigneePaymentID", DbType="Int NOT NULL")]
		public int ConsigneePaymentID
		{
			get
			{
				return this._ConsigneePaymentID;
			}
			set
			{
				if ((this._ConsigneePaymentID != value))
				{
					if (this._ConsigneePayment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConsigneePaymentIDChanging(value);
					this.SendPropertyChanging();
					this._ConsigneePaymentID = value;
					this.SendPropertyChanged("ConsigneePaymentID");
					this.OnConsigneePaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialAgreements", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string SpecialAgreements
		{
			get
			{
				return this._SpecialAgreements;
			}
			set
			{
				if ((this._SpecialAgreements != value))
				{
					this.OnSpecialAgreementsChanging(value);
					this.SendPropertyChanging();
					this._SpecialAgreements = value;
					this.SendPropertyChanged("SpecialAgreements");
					this.OnSpecialAgreementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentInstruction", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PaymentInstruction
		{
			get
			{
				return this._PaymentInstruction;
			}
			set
			{
				if ((this._PaymentInstruction != value))
				{
					this.OnPaymentInstructionChanging(value);
					this.SendPropertyChanging();
					this._PaymentInstruction = value;
					this.SendPropertyChanged("PaymentInstruction");
					this.OnPaymentInstructionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMRValid", DbType="Bit NOT NULL")]
		public bool CMRValid
		{
			get
			{
				return this._CMRValid;
			}
			set
			{
				if ((this._CMRValid != value))
				{
					this.OnCMRValidChanging(value);
					this.SendPropertyChanging();
					this._CMRValid = value;
					this.SendPropertyChanged("CMRValid");
					this.OnCMRValidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstablieshedIn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EstablieshedIn
		{
			get
			{
				return this._EstablieshedIn;
			}
			set
			{
				if ((this._EstablieshedIn != value))
				{
					this.OnEstablieshedInChanging(value);
					this.SendPropertyChanging();
					this._EstablieshedIn = value;
					this.SendPropertyChanged("EstablieshedIn");
					this.OnEstablieshedInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstablieshedDate", DbType="DateTime NOT NULL")]
		public System.DateTime EstablieshedDate
		{
			get
			{
				return this._EstablieshedDate;
			}
			set
			{
				if ((this._EstablieshedDate != value))
				{
					this.OnEstablieshedDateChanging(value);
					this.SendPropertyChanging();
					this._EstablieshedDate = value;
					this.SendPropertyChanged("EstablieshedDate");
					this.OnEstablieshedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOfDep", DbType="DateTime NOT NULL")]
		public System.DateTime TimeOfDep
		{
			get
			{
				return this._TimeOfDep;
			}
			set
			{
				if ((this._TimeOfDep != value))
				{
					this.OnTimeOfDepChanging(value);
					this.SendPropertyChanging();
					this._TimeOfDep = value;
					this.SendPropertyChanged("TimeOfDep");
					this.OnTimeOfDepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportID", DbType="Int NOT NULL")]
		public int TransportID
		{
			get
			{
				return this._TransportID;
			}
			set
			{
				if ((this._TransportID != value))
				{
					if (this._Transport.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransportIDChanging(value);
					this.SendPropertyChanging();
					this._TransportID = value;
					this.SendPropertyChanged("TransportID");
					this.OnTransportIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportID2", DbType="Int")]
		public System.Nullable<int> TransportID2
		{
			get
			{
				return this._TransportID2;
			}
			set
			{
				if ((this._TransportID2 != value))
				{
					this.OnTransportID2Changing(value);
					this.SendPropertyChanging();
					this._TransportID2 = value;
					this.SendPropertyChanged("TransportID2");
					this.OnTransportID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreated", DbType="VarChar(50)")]
		public string UserCreated
		{
			get
			{
				return this._UserCreated;
			}
			set
			{
				if ((this._UserCreated != value))
				{
					this.OnUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._UserCreated = value;
					this.SendPropertyChanged("UserCreated");
					this.OnUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManifestId", DbType="Int")]
		public System.Nullable<int> ManifestId
		{
			get
			{
				return this._ManifestId;
			}
			set
			{
				if ((this._ManifestId != value))
				{
					if (this._Manifest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManifestIdChanging(value);
					this.SendPropertyChanging();
					this._ManifestId = value;
					this.SendPropertyChanged("ManifestId");
					this.OnManifestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CMR_OrderItem", Storage="_OrderItems", ThisKey="ID", OtherKey="CMRID")]
		public EntitySet<OrderItem> OrderItems
		{
			get
			{
				return this._OrderItems;
			}
			set
			{
				this._OrderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentInfo_CMR", Storage="_ConsigneePayment", ThisKey="ConsigneePaymentID", OtherKey="ID", IsForeignKey=true)]
		public PaymentInfo ConsigneePayment
		{
			get
			{
				return this._ConsigneePayment.Entity;
			}
			set
			{
				PaymentInfo previousValue = this._ConsigneePayment.Entity;
				if (((previousValue != value) 
							|| (this._ConsigneePayment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ConsigneePayment.Entity = null;
						previousValue.CMRs.Remove(this);
					}
					this._ConsigneePayment.Entity = value;
					if ((value != null))
					{
						value.CMRs.Add(this);
						this._ConsigneePaymentID = value.ID;
					}
					else
					{
						this._ConsigneePaymentID = default(int);
					}
					this.SendPropertyChanged("ConsigneePayment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manifest_CMR", Storage="_Manifest", ThisKey="ManifestId", OtherKey="id", IsForeignKey=true)]
		public Manifest Manifest
		{
			get
			{
				return this._Manifest.Entity;
			}
			set
			{
				Manifest previousValue = this._Manifest.Entity;
				if (((previousValue != value) 
							|| (this._Manifest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Manifest.Entity = null;
						previousValue.CMRs.Remove(this);
					}
					this._Manifest.Entity = value;
					if ((value != null))
					{
						value.CMRs.Add(this);
						this._ManifestId = value.id;
					}
					else
					{
						this._ManifestId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Manifest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transport_CMR", Storage="_Transport", ThisKey="TransportID", OtherKey="ID", IsForeignKey=true)]
		public Transport Transport
		{
			get
			{
				return this._Transport.Entity;
			}
			set
			{
				Transport previousValue = this._Transport.Entity;
				if (((previousValue != value) 
							|| (this._Transport.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transport.Entity = null;
						previousValue.CMRs.Remove(this);
					}
					this._Transport.Entity = value;
					if ((value != null))
					{
						value.CMRs.Add(this);
						this._TransportID = value.ID;
					}
					else
					{
						this._TransportID = default(int);
					}
					this.SendPropertyChanged("Transport");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentInfo_CMR1", Storage="_SenderPayment", ThisKey="SenderPaymentID", OtherKey="ID", IsForeignKey=true)]
		public PaymentInfo SenderPayment
		{
			get
			{
				return this._SenderPayment.Entity;
			}
			set
			{
				PaymentInfo previousValue = this._SenderPayment.Entity;
				if (((previousValue != value) 
							|| (this._SenderPayment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SenderPayment.Entity = null;
						previousValue.CMRs1.Remove(this);
					}
					this._SenderPayment.Entity = value;
					if ((value != null))
					{
						value.CMRs1.Add(this);
						this._SenderPaymentID = value.ID;
					}
					else
					{
						this._SenderPaymentID = default(int);
					}
					this.SendPropertyChanged("SenderPayment");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.CMR = this;
		}
		
		private void detach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.CMR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _InvDate;
		
		private int _CompanyToID;
		
		private int _GeneratedByUserID;
		
		private int _OrderNr;
		
		private bool _RemarkUrgent;
		
		private bool _RemarkForReview;
		
		private bool _RemarkASAP;
		
		private bool _RemarkComment;
		
		private string _Cruise;
		
		private string _CargoDescription;
		
		private string _LoadingTime;
		
		private string _LoadingPlace;
		
		private string _DispatchTime;
		
		private string _DispatchPlace;
		
		private string _DispatchContact;
		
		private string _PriceInfo;
		
		private string _PaymentTerms;
		
		private string _TransportInfo;
		
		private string _UserNotes;
		
		private string _UserCreated;
		
		private string _ContactPhoneNumber;
		
		private EntityRef<Company> _CompanyTo;
		
		private EntityRef<User> _GeneratedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInvDateChanging(System.DateTime value);
    partial void OnInvDateChanged();
    partial void OnCompanyToIDChanging(int value);
    partial void OnCompanyToIDChanged();
    partial void OnGeneratedByUserIDChanging(int value);
    partial void OnGeneratedByUserIDChanged();
    partial void OnOrderNrChanging(int value);
    partial void OnOrderNrChanged();
    partial void OnRemarkUrgentChanging(bool value);
    partial void OnRemarkUrgentChanged();
    partial void OnRemarkForReviewChanging(bool value);
    partial void OnRemarkForReviewChanged();
    partial void OnRemarkASAPChanging(bool value);
    partial void OnRemarkASAPChanged();
    partial void OnRemarkCommentChanging(bool value);
    partial void OnRemarkCommentChanged();
    partial void OnCruiseChanging(string value);
    partial void OnCruiseChanged();
    partial void OnCargoDescriptionChanging(string value);
    partial void OnCargoDescriptionChanged();
    partial void OnLoadingTimeChanging(string value);
    partial void OnLoadingTimeChanged();
    partial void OnLoadingPlaceChanging(string value);
    partial void OnLoadingPlaceChanged();
    partial void OnDispatchTimeChanging(string value);
    partial void OnDispatchTimeChanged();
    partial void OnDispatchPlaceChanging(string value);
    partial void OnDispatchPlaceChanged();
    partial void OnDispatchContactChanging(string value);
    partial void OnDispatchContactChanged();
    partial void OnPriceInfoChanging(string value);
    partial void OnPriceInfoChanged();
    partial void OnPaymentTermsChanging(string value);
    partial void OnPaymentTermsChanged();
    partial void OnTransportInfoChanging(string value);
    partial void OnTransportInfoChanged();
    partial void OnUserNotesChanging(string value);
    partial void OnUserNotesChanged();
    partial void OnUserCreatedChanging(string value);
    partial void OnUserCreatedChanged();
    partial void OnContactPhoneNumberChanging(string value);
    partial void OnContactPhoneNumberChanged();
    #endregion
		
		public Invoice()
		{
			this._CompanyTo = default(EntityRef<Company>);
			this._GeneratedBy = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvDate", DbType="DateTime NOT NULL")]
		public System.DateTime InvDate
		{
			get
			{
				return this._InvDate;
			}
			set
			{
				if ((this._InvDate != value))
				{
					this.OnInvDateChanging(value);
					this.SendPropertyChanging();
					this._InvDate = value;
					this.SendPropertyChanged("InvDate");
					this.OnInvDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyToID", DbType="Int NOT NULL")]
		public int CompanyToID
		{
			get
			{
				return this._CompanyToID;
			}
			set
			{
				if ((this._CompanyToID != value))
				{
					if (this._CompanyTo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompanyToIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyToID = value;
					this.SendPropertyChanged("CompanyToID");
					this.OnCompanyToIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneratedByUserID", DbType="Int NOT NULL")]
		public int GeneratedByUserID
		{
			get
			{
				return this._GeneratedByUserID;
			}
			set
			{
				if ((this._GeneratedByUserID != value))
				{
					if (this._GeneratedBy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGeneratedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._GeneratedByUserID = value;
					this.SendPropertyChanged("GeneratedByUserID");
					this.OnGeneratedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNr", DbType="Int")]
		public int OrderNr
		{
			get
			{
				return this._OrderNr;
			}
			set
			{
				if ((this._OrderNr != value))
				{
					this.OnOrderNrChanging(value);
					this.SendPropertyChanging();
					this._OrderNr = value;
					this.SendPropertyChanged("OrderNr");
					this.OnOrderNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkUrgent", DbType="Bit NOT NULL")]
		public bool RemarkUrgent
		{
			get
			{
				return this._RemarkUrgent;
			}
			set
			{
				if ((this._RemarkUrgent != value))
				{
					this.OnRemarkUrgentChanging(value);
					this.SendPropertyChanging();
					this._RemarkUrgent = value;
					this.SendPropertyChanged("RemarkUrgent");
					this.OnRemarkUrgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkForReview", DbType="Bit NOT NULL")]
		public bool RemarkForReview
		{
			get
			{
				return this._RemarkForReview;
			}
			set
			{
				if ((this._RemarkForReview != value))
				{
					this.OnRemarkForReviewChanging(value);
					this.SendPropertyChanging();
					this._RemarkForReview = value;
					this.SendPropertyChanged("RemarkForReview");
					this.OnRemarkForReviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkASAP", DbType="Bit NOT NULL")]
		public bool RemarkASAP
		{
			get
			{
				return this._RemarkASAP;
			}
			set
			{
				if ((this._RemarkASAP != value))
				{
					this.OnRemarkASAPChanging(value);
					this.SendPropertyChanging();
					this._RemarkASAP = value;
					this.SendPropertyChanged("RemarkASAP");
					this.OnRemarkASAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkComment", DbType="Bit NOT NULL")]
		public bool RemarkComment
		{
			get
			{
				return this._RemarkComment;
			}
			set
			{
				if ((this._RemarkComment != value))
				{
					this.OnRemarkCommentChanging(value);
					this.SendPropertyChanging();
					this._RemarkComment = value;
					this.SendPropertyChanged("RemarkComment");
					this.OnRemarkCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cruise", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Cruise
		{
			get
			{
				return this._Cruise;
			}
			set
			{
				if ((this._Cruise != value))
				{
					this.OnCruiseChanging(value);
					this.SendPropertyChanging();
					this._Cruise = value;
					this.SendPropertyChanged("Cruise");
					this.OnCruiseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoDescription", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CargoDescription
		{
			get
			{
				return this._CargoDescription;
			}
			set
			{
				if ((this._CargoDescription != value))
				{
					this.OnCargoDescriptionChanging(value);
					this.SendPropertyChanging();
					this._CargoDescription = value;
					this.SendPropertyChanged("CargoDescription");
					this.OnCargoDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingTime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LoadingTime
		{
			get
			{
				return this._LoadingTime;
			}
			set
			{
				if ((this._LoadingTime != value))
				{
					this.OnLoadingTimeChanging(value);
					this.SendPropertyChanging();
					this._LoadingTime = value;
					this.SendPropertyChanged("LoadingTime");
					this.OnLoadingTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingPlace", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string LoadingPlace
		{
			get
			{
				return this._LoadingPlace;
			}
			set
			{
				if ((this._LoadingPlace != value))
				{
					this.OnLoadingPlaceChanging(value);
					this.SendPropertyChanging();
					this._LoadingPlace = value;
					this.SendPropertyChanged("LoadingPlace");
					this.OnLoadingPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchTime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DispatchTime
		{
			get
			{
				return this._DispatchTime;
			}
			set
			{
				if ((this._DispatchTime != value))
				{
					this.OnDispatchTimeChanging(value);
					this.SendPropertyChanging();
					this._DispatchTime = value;
					this.SendPropertyChanged("DispatchTime");
					this.OnDispatchTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchPlace", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DispatchPlace
		{
			get
			{
				return this._DispatchPlace;
			}
			set
			{
				if ((this._DispatchPlace != value))
				{
					this.OnDispatchPlaceChanging(value);
					this.SendPropertyChanging();
					this._DispatchPlace = value;
					this.SendPropertyChanged("DispatchPlace");
					this.OnDispatchPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchContact", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DispatchContact
		{
			get
			{
				return this._DispatchContact;
			}
			set
			{
				if ((this._DispatchContact != value))
				{
					this.OnDispatchContactChanging(value);
					this.SendPropertyChanging();
					this._DispatchContact = value;
					this.SendPropertyChanged("DispatchContact");
					this.OnDispatchContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceInfo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PriceInfo
		{
			get
			{
				return this._PriceInfo;
			}
			set
			{
				if ((this._PriceInfo != value))
				{
					this.OnPriceInfoChanging(value);
					this.SendPropertyChanging();
					this._PriceInfo = value;
					this.SendPropertyChanged("PriceInfo");
					this.OnPriceInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this.OnPaymentTermsChanging(value);
					this.SendPropertyChanging();
					this._PaymentTerms = value;
					this.SendPropertyChanged("PaymentTerms");
					this.OnPaymentTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportInfo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TransportInfo
		{
			get
			{
				return this._TransportInfo;
			}
			set
			{
				if ((this._TransportInfo != value))
				{
					this.OnTransportInfoChanging(value);
					this.SendPropertyChanging();
					this._TransportInfo = value;
					this.SendPropertyChanged("TransportInfo");
					this.OnTransportInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNotes", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string UserNotes
		{
			get
			{
				return this._UserNotes;
			}
			set
			{
				if ((this._UserNotes != value))
				{
					this.OnUserNotesChanging(value);
					this.SendPropertyChanging();
					this._UserNotes = value;
					this.SendPropertyChanged("UserNotes");
					this.OnUserNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreated", DbType="VarChar(50)")]
		public string UserCreated
		{
			get
			{
				return this._UserCreated;
			}
			set
			{
				if ((this._UserCreated != value))
				{
					this.OnUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._UserCreated = value;
					this.SendPropertyChanged("UserCreated");
					this.OnUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhoneNumber", DbType="VarChar(20)")]
		public string ContactPhoneNumber
		{
			get
			{
				return this._ContactPhoneNumber;
			}
			set
			{
				if ((this._ContactPhoneNumber != value))
				{
					this.OnContactPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactPhoneNumber = value;
					this.SendPropertyChanged("ContactPhoneNumber");
					this.OnContactPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Invoice", Storage="_CompanyTo", ThisKey="CompanyToID", OtherKey="ID", IsForeignKey=true)]
		public Company CompanyTo
		{
			get
			{
				return this._CompanyTo.Entity;
			}
			set
			{
				Company previousValue = this._CompanyTo.Entity;
				if (((previousValue != value) 
							|| (this._CompanyTo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CompanyTo.Entity = null;
						previousValue.Invoices.Remove(this);
					}
					this._CompanyTo.Entity = value;
					if ((value != null))
					{
						value.Invoices.Add(this);
						this._CompanyToID = value.ID;
					}
					else
					{
						this._CompanyToID = default(int);
					}
					this.SendPropertyChanged("CompanyTo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Invoice", Storage="_GeneratedBy", ThisKey="GeneratedByUserID", OtherKey="ID", IsForeignKey=true)]
		public User GeneratedBy
		{
			get
			{
				return this._GeneratedBy.Entity;
			}
			set
			{
				User previousValue = this._GeneratedBy.Entity;
				if (((previousValue != value) 
							|| (this._GeneratedBy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GeneratedBy.Entity = null;
						previousValue.Invoices.Remove(this);
					}
					this._GeneratedBy.Entity = value;
					if ((value != null))
					{
						value.Invoices.Add(this);
						this._GeneratedByUserID = value.ID;
					}
					else
					{
						this._GeneratedByUserID = default(int);
					}
					this.SendPropertyChanged("GeneratedBy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderDispatch")]
	public partial class OrderDispatch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Order_id;
		
		private string _DispatchTime;
		
		private string _DispatchPlace;
		
		private string _DispatchContact;
		
		private string _DispatchType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnOrder_idChanging(int value);
    partial void OnOrder_idChanged();
    partial void OnDispatchTimeChanging(string value);
    partial void OnDispatchTimeChanged();
    partial void OnDispatchPlaceChanging(string value);
    partial void OnDispatchPlaceChanged();
    partial void OnDispatchContactChanging(string value);
    partial void OnDispatchContactChanged();
    partial void OnDispatchTypeChanging(string value);
    partial void OnDispatchTypeChanged();
    #endregion
		
		public OrderDispatch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_id", DbType="Int NOT NULL")]
		public int Order_id
		{
			get
			{
				return this._Order_id;
			}
			set
			{
				if ((this._Order_id != value))
				{
					this.OnOrder_idChanging(value);
					this.SendPropertyChanging();
					this._Order_id = value;
					this.SendPropertyChanged("Order_id");
					this.OnOrder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchTime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DispatchTime
		{
			get
			{
				return this._DispatchTime;
			}
			set
			{
				if ((this._DispatchTime != value))
				{
					this.OnDispatchTimeChanging(value);
					this.SendPropertyChanging();
					this._DispatchTime = value;
					this.SendPropertyChanged("DispatchTime");
					this.OnDispatchTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchPlace", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DispatchPlace
		{
			get
			{
				return this._DispatchPlace;
			}
			set
			{
				if ((this._DispatchPlace != value))
				{
					this.OnDispatchPlaceChanging(value);
					this.SendPropertyChanging();
					this._DispatchPlace = value;
					this.SendPropertyChanged("DispatchPlace");
					this.OnDispatchPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchContact", DbType="VarChar(50)")]
		public string DispatchContact
		{
			get
			{
				return this._DispatchContact;
			}
			set
			{
				if ((this._DispatchContact != value))
				{
					this.OnDispatchContactChanging(value);
					this.SendPropertyChanging();
					this._DispatchContact = value;
					this.SendPropertyChanged("DispatchContact");
					this.OnDispatchContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchType", DbType="VarChar(1)")]
		public string DispatchType
		{
			get
			{
				return this._DispatchType;
			}
			set
			{
				if ((this._DispatchType != value))
				{
					this.OnDispatchTypeChanging(value);
					this.SendPropertyChanging();
					this._DispatchType = value;
					this.SendPropertyChanged("DispatchType");
					this.OnDispatchTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
