<?xml version="1.0" encoding="utf-8"?><Database Name="BeLogDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=BeLogDB;Integrated Security=True" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="BeLogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactPerson" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Company_Invoice" Member="Invoices" ThisKey="ID" OtherKey="CompanyToID" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CMRID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MarkAndNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumOfPackages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PackagingMethod" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GoodsNature" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StartNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Association Name="CMR_OrderItem" Member="CMR" ThisKey="CMRID" OtherKey="ID" Type="CMR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentInfo" Member="PaymentInfos">
    <Type Name="PaymentInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarriageCharges" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Deductions" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Supplements" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="OtherCharges" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="PaymentInfo_CMR" Member="CMRs" ThisKey="ID" OtherKey="ConsigneePaymentID" Type="CMR" />
      <Association Name="PaymentInfo_CMR1" Member="CMRs1" ThisKey="ID" OtherKey="SenderPaymentID" Type="CMR" />
    </Type>
  </Table>
  <Table Name="dbo.Transport" Member="Transports">
    <Type Name="Transport">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Transport_CMR" Member="CMRs" ThisKey="ID" OtherKey="TransportID" Type="CMR" />
    </Type>
  </Table>
  <Table Name="dbo.BFUser" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginUserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoginPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationRights" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Abreviation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="ID" OtherKey="GeneratedByUserID" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Manifest" Member="Manifests">
    <Type Name="Manifest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Departure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Arrival" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ManifestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ManifesName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Association Name="Manifest_CMR" Member="CMRs" ThisKey="id" OtherKey="ManifestId" Type="CMR" />
    </Type>
  </Table>
  <Table Name="dbo.CMR" Member="CMRs">
    <Type Name="CMR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConsigneeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryPlace" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryCountry" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TakingPlace" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TakingCountry" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AttachedDocuments" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CarrierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NextCarrierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassValue" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Letter" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ADR" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SendInstruction" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SenderPaymentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConsigneePaymentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAgreements" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentInstruction" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CMRValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EstablieshedIn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EstablieshedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeOfDep" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TransportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransportID2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ManifestId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CMR_OrderItem" Member="OrderItems" ThisKey="ID" OtherKey="CMRID" Type="OrderItem" />
      <Association Name="PaymentInfo_CMR" Member="ConsigneePayment" ThisKey="ConsigneePaymentID" OtherKey="ID" Type="PaymentInfo" IsForeignKey="true" />
      <Association Name="Manifest_CMR" Member="Manifest" ThisKey="ManifestId" OtherKey="id" Type="Manifest" IsForeignKey="true" />
      <Association Name="Transport_CMR" Member="Transport" ThisKey="TransportID" OtherKey="ID" Type="Transport" IsForeignKey="true" />
      <Association Name="PaymentInfo_CMR1" Member="SenderPayment" ThisKey="SenderPaymentID" OtherKey="ID" Type="PaymentInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompanyToID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GeneratedByUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderNr" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="RemarkUrgent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RemarkForReview" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RemarkASAP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RemarkComment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Cruise" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CargoDescription" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LoadingTime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoadingPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchTime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchContact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceInfo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTerms" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TransportInfo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserNotes" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserCreated" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactPhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Company_Invoice" Member="CompanyTo" ThisKey="CompanyToID" OtherKey="ID" Type="Company" IsForeignKey="true" />
      <Association Name="User_Invoice" Member="GeneratedBy" ThisKey="GeneratedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDispatch" Member="OrderDispatches">
    <Type Name="OrderDispatch">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DispatchTime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchPlace" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchContact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DispatchType" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>