//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLogForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeLogForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia ja Montenegro CS
        ///Läti LV
        ///Liibüa LY
        ///Maroko MA
        ///Moldova MD
        ///Madagaskar MG
        ///Marshalli saared MH
        ///Makedoonia MK
        ///Mali ML
        ///Mongoolia MN
        ///Macau MO
        ///Põhja-Mariaanid MP
        ///Martinique MQ
        ///Montserrat MS
        ///Malta MT
        ///Mauritius MU
        ///Maldiivid MV
        ///Malawi MW
        ///Mehhiko MX
        ///Malaisia MY
        ///Mosambiik MZ
        ///Namiibia NA
        ///Uus-Kaledoonia NC
        ///Norfolki saared NF
        ///Nigeeria NG
        ///Nikaraagua NI
        ///Holland NL
        ///Norra NO
        ///Nepaal NP
        ///Nauru NR
        ///Uus-Meremaa NZ
        ///Omaan OM
        ///Panama PA
        ///Peruu PE
        ///Prantsuse Polüneesia PF
        ///Paapua Uus-Guinea PG
        ///Filip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED	United Arab Emirates, Dirhams
        ///AFN	Afghanistan, Afghanis
        ///ALL	Albania, Leke
        ///AMD	Armenia, Drams
        ///ANG	Netherlands Antilles, Guilders 
        ///AOA	Angola, Kwanza
        ///ARS	Argentina, Pesos
        ///AUD	Australia, Dollars
        ///AWG	Aruba, Guilders 
        ///AZN	Azerbaijan, New Manats
        ///BAM	Bosnia and Herzegovina, Convertible Marka
        ///BBD	Barbados, Dollars
        ///BDT	Bangladesh, Taka
        ///BGN	Bulgaria, Leva
        ///BHD	Bahrain, Dinars
        ///BIF	Burundi, Francs
        ///BMD	Bermuda, Dollars
        ///BND	Brunei Darussalam, Dollars
        ///BOB	Bolivia, Bolivianos
        ///BRL	Brazil, Brazil Real
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CurrencyList {
            get {
                return ResourceManager.GetString("CurrencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EE
        ///LT
        ///LV
        ///BY
        ///FI
        ///GB
        ///BE
        ///DE
        ///RU
        ///IT
        ///NL
        ///SE
        ///US
        ///DK
        ///FR
        ///CZ
        ///AT.
        /// </summary>
        internal static string PriorCountries {
            get {
                return ResourceManager.GetString("PriorCountries", resourceCulture);
            }
        }
    }
}
